### ISSUE TITLE
Facebook providers did not provide user's email.

### ISSUE THREAD

**Issue by maxtortime** [wooyek/flask-social-blueprint#7]
I think this problem based on Facebook Graph Api versions.
Graph api versions is upgraded to 2.4.
They're not provide email exactly. 
Graph API ver 2.3
curl -i -X GET \
 "https://graph.facebook.com/v2.3/me?access_token=..." // can get email
Graph API ver 2.4.
curl -i -X GET \
 "https://graph.facebook.com/v2.3/me?access_token=..." // cannot get email

Therefore, I think you should change 'facebook' class in providers.py.
just 
'profile = graph.get_object("me?fields=email")'

I think all libraries based on flask-oauth should be changed.
Thank you!

**Comment by wooyek** [comment]
I not sure what's wrong, when I login with Facebook i get the email:

Please try it here, http://flask-social-blueprint.appspot.com/ - test database was cleared.

**Comment by danielhomola** [comment]
@maxtortime was definitely right.. I spent a good 2 hours to figure this s.. out.. Since GraphAPI ver 2.4 you need to explicitly specify all the fields you want, 
profile = graph.get_object("me")
should be changed to:
profile = graph.get_object("me?fields=email,first_name,last_name,name")
otherwise you WILL NOT get email address. I have no idea how it works for you, but I'm sure it won't work for many people out there, so you might as well change it..

thanks again for your work, cheers,
Dan
